### ISSUE TITLE
SCP policy feature

### ISSUE THREAD

**Issue by galaxyware241** [orcasecurity/orca-toolbox#16]
hi,
I'm trying to run this against the policy file downloaded using get get-account-authorisation-details, but it seems it doesn't consider SCP policies. Do we have to download the SCPp policies separately? Not sure if it is reflected in the document. 

Thanks,
A.

**Comment by Tohar-orca** [comment]
Hey @galaxyware241, you can provide an SCP policy with the `-s / --scp-policy` flag
To get the policies, run `aws organizations list-policies-for-target --target-id <ACCOUNT_ID> --filter SERVICE_CONTROL_POLICY` to list the relevant policy ID's for you account, then `aws organizations describe-policy --policy-id <SCP_Policy_ID>` to get the policy itself
