### ISSUE TITLE
error when I run the command: iam-ape --arn arn:aws:iam::<account_id>:role/role

### ISSUE THREAD

**Issue by jhonnatan-costa** [orcasecurity/orca-toolbox#4]
I have an error when I run the command: iam-ape --arn arn:aws:iam::069560771595:role/account-creation-foundation

ERROR: Failed to load AWS IAM Actions due to file could not be opened successfully
File "c:\users\jhonnatan.costa\anaconda3\lib\site-packages\iam_ape\expand_policy.py", line 153, in expand_action
for action in self.all_iam_actions[service].keys():
KeyError: 'servicecatalog'

**Comment by Tohar-orca** [comment]
Hey @jhonnatan-costa thanks for your feedback. The issue should now be resolved with the latest 1.1.0 release
