### ISSUE TITLE
iam-ape: Loosen the ARN match pattern

### ISSUE THREAD

**Issue by ashi009** [orcasecurity/orca-toolbox#9]
AWS creates roles with forward-slashes in the resource name part (eg. `role/aws-reserved/sso.amazonaws.com/xxx`, `role/service-role/xxx`),
and the current regexp will mark them as invalid.

**Comment by ashi009** [comment]
https://github.com/orcasecurity/orca-toolbox/blob/5edcf2562f30c9ae87cb3fbc83086a638d768ff6/iam-ape/iam_ape/main.py#L19-L21

**Comment by Tohar-orca** [comment]
fixed in #11
